version: '2.1'
services:
  bot:
    build: .
    restart: on-failure
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./groupwelcome.sql:/docker-entrypoint-initdb.d/0_init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
